# Generated by Django 5.2.12 on 2026-10-05 15:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('certification_number', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'city'), name='office_name_city_unique')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='VIN must be 17 characters (letters and digits, excluding I, O and Q).', regex='^[A-HJ-NPR-Z0-9]{17}$')], verbose_name='VIN')),
                ('license_plate', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
                ('is_active', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet.office')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_date', models.DateField()),
                ('maintenance_type', models.CharField(choices=[('oil_change', 'Oil change'), ('tire_rotation', 'Tire rotation'), ('brake_service', 'Brake service'), ('inspection', 'Inspection'), ('engine_repair', 'Engine repair'), ('transmission_service', 'Transmission service'), ('battery', 'Battery'), ('other', 'Other')], max_length=32)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notes', models.TextField(blank=True)),
                ('mechanic', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='fleet.mechanic')),
                ('vehicle', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='fleet.vehicle')),
            ],
            options={
                'ordering': ['-maintenance_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['make', 'model'], name='vehicle_make_model_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('license_plate',), name='vehicle_active_license_plate_unique', violation_error_message='An active vehicle with this license plate already exists.'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 1900)), name='vehicle_year_min'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['vehicle', '-maintenance_date'], name='maintenance_vehicle_date_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancerecord',
            index=models.Index(fields=['mechanic', 'maintenance_date'], name='maintenance_mechanic_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='maintenancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='maintenance_cost_non_negative'),
        ),
    ]
