# Generated by Django 5.2.12 on 2026-10-05 16:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicle',
            name='vehicle_make_model_idx',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(django.db.models.functions.text.Upper('make'), django.db.models.functions.text.Upper('model'), name='vehicle_upper_make_model_idx'),
        ),
    ]
