# Generated by Django 5.2.12 on 2026-10-06 08:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['submission', '-created_at'], name='note_submission_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status'], name='submission_status_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['priority'], name='submission_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['-created_at'], name='submission_created_at_idx'),
        ),
    ]
