/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/token/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/token/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Liveness probe that also verifies the database is reachable. */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance-records/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Maintenance performed on a vehicle by a mechanic. */
        get: operations["maintenance_records_list"];
        put?: never;
        /** @description Maintenance performed on a vehicle by a mechanic. */
        post: operations["maintenance_records_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/maintenance-records/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Maintenance performed on a vehicle by a mechanic. */
        get: operations["maintenance_records_retrieve"];
        /** @description Maintenance performed on a vehicle by a mechanic. */
        put: operations["maintenance_records_update"];
        post?: never;
        /** @description Maintenance performed on a vehicle by a mechanic. */
        delete: operations["maintenance_records_destroy"];
        options?: never;
        head?: never;
        /** @description Maintenance performed on a vehicle by a mechanic. */
        patch: operations["maintenance_records_partial_update"];
        trace?: never;
    };
    "/api/mechanics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mechanics who perform maintenance. Inactive mechanics cannot take new work. */
        get: operations["mechanics_list"];
        put?: never;
        /** @description Mechanics who perform maintenance. Inactive mechanics cannot take new work. */
        post: operations["mechanics_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mechanics/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mechanics who perform maintenance. Inactive mechanics cannot take new work. */
        get: operations["mechanics_retrieve"];
        /** @description Mechanics who perform maintenance. Inactive mechanics cannot take new work. */
        put: operations["mechanics_update"];
        post?: never;
        /** @description Mechanics who perform maintenance. Inactive mechanics cannot take new work. */
        delete: operations["mechanics_destroy"];
        options?: never;
        head?: never;
        /** @description Mechanics who perform maintenance. Inactive mechanics cannot take new work. */
        patch: operations["mechanics_partial_update"];
        trace?: never;
    };
    "/api/mechanics/workload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mechanic workload for a year, busiest first
         * @description Number of maintenance records and their total cost per mechanic for the given year (default: current year). Mechanics without work are included with zeros.
         */
        get: operations["mechanics_workload_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Offices that vehicles are assigned to. */
        get: operations["offices_list"];
        put?: never;
        /** @description Offices that vehicles are assigned to. */
        post: operations["offices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Offices that vehicles are assigned to. */
        get: operations["offices_retrieve"];
        /** @description Offices that vehicles are assigned to. */
        put: operations["offices_update"];
        post?: never;
        /** @description Offices that vehicles are assigned to. */
        delete: operations["offices_destroy"];
        options?: never;
        head?: never;
        /** @description Offices that vehicles are assigned to. */
        patch: operations["offices_partial_update"];
        trace?: never;
    };
    "/api/offices/summary/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fleet statistics for every office
         * @description Active vehicle count, maintenance cost over the last 365 days and the date of the most recent maintenance on any of the office's vehicles.
         */
        get: operations["offices_summary_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fleet vehicles. VIN and license plate are stored in upper case. */
        get: operations["vehicles_list"];
        put?: never;
        /** @description Fleet vehicles. VIN and license plate are stored in upper case. */
        post: operations["vehicles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fleet vehicles. VIN and license plate are stored in upper case. */
        get: operations["vehicles_retrieve"];
        /** @description Fleet vehicles. VIN and license plate are stored in upper case. */
        put: operations["vehicles_update"];
        post?: never;
        /** @description Fleet vehicles. VIN and license plate are stored in upper case. */
        delete: operations["vehicles_destroy"];
        options?: never;
        head?: never;
        /** @description Fleet vehicles. VIN and license plate are stored in upper case. */
        patch: operations["vehicles_partial_update"];
        trace?: never;
    };
    "/api/vehicles/{id}/assign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move a vehicle to another office
         * @description Only the office assignment is written; other vehicle fields are untouched.
         */
        post: operations["vehicles_assign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/{id}/maintenance-history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Maintenance history of a vehicle, newest first
         * @description Fleet vehicles. VIN and license plate are stored in upper case.
         */
        get: operations["vehicles_maintenance_history_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/duplicate-check/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check whether a VIN or license plate is already taken
         * @description A VIN conflicts with any other vehicle; a license plate only with another active vehicle.
         */
        get: operations["vehicles_duplicate_check_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vehicles/needing-maintenance/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active vehicles due for maintenance
         * @description Active vehicles that were never serviced or were last serviced more than 365 days ago, oldest maintenance first. Never-serviced vehicles are listed first.
         */
        get: operations["vehicles_needing_maintenance_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `vin` - vin
         *     * `license_plate` - license_plate
         * @enum {string}
         */
        ConflictsEnum: "vin" | "license_plate";
        /**
         * @description * `ok` - ok
         *     * `unavailable` - unavailable
         * @enum {string}
         */
        DatabaseEnum: "ok" | "unavailable";
        DuplicateCheck: {
            conflicts: components["schemas"]["ConflictsEnum"][];
        };
        ErrorDetail: {
            detail: string;
        };
        HealthCheck: {
            status: components["schemas"]["StatusEnum"];
            database: components["schemas"]["DatabaseEnum"];
        };
        MaintenanceRecord: {
            readonly id: number;
            vehicle: number;
            mechanic: number;
            /** Format: date */
            maintenance_date: string;
            maintenance_type: components["schemas"]["MaintenanceTypeEnum"];
            /** Format: double */
            cost: number;
            notes?: string;
        };
        MaintenanceRecordRequest: {
            vehicle: number;
            mechanic: number;
            /** Format: date */
            maintenance_date: string;
            maintenance_type: components["schemas"]["MaintenanceTypeEnum"];
            /** Format: double */
            cost: number;
            notes?: string;
        };
        /**
         * @description * `oil_change` - Oil change
         *     * `tire_rotation` - Tire rotation
         *     * `brake_service` - Brake service
         *     * `inspection` - Inspection
         *     * `engine_repair` - Engine repair
         *     * `transmission_service` - Transmission service
         *     * `battery` - Battery
         *     * `other` - Other
         * @enum {string}
         */
        MaintenanceTypeEnum: "oil_change" | "tire_rotation" | "brake_service" | "inspection" | "engine_repair" | "transmission_service" | "battery" | "other";
        Mechanic: {
            readonly id: number;
            name: string;
            certification_number: string;
            is_active?: boolean;
        };
        MechanicRequest: {
            name: string;
            certification_number: string;
            is_active?: boolean;
        };
        MechanicWorkload: {
            readonly id: number;
            name: string;
            certification_number: string;
            readonly maintenance_record_count: number;
            /** Format: double */
            readonly total_maintenance_cost: number;
        };
        Office: {
            readonly id: number;
            name: string;
            city: string;
        };
        OfficeRequest: {
            name: string;
            city: string;
        };
        OfficeSummary: {
            readonly id: number;
            name: string;
            city: string;
            readonly active_vehicle_count: number;
            /** Format: double */
            readonly maintenance_cost_last_year: number;
            /** Format: date */
            readonly last_maintenance: string | null;
        };
        PaginatedMaintenanceRecordList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["MaintenanceRecord"][];
        };
        PaginatedMechanicList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Mechanic"][];
        };
        PaginatedOfficeList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Office"][];
        };
        PaginatedVehicleList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Vehicle"][];
        };
        PaginatedVehicleMaintenanceRecordList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["VehicleMaintenanceRecord"][];
        };
        PaginatedVehicleNeedingMaintenanceList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["VehicleNeedingMaintenance"][];
        };
        PatchedMaintenanceRecordRequest: {
            vehicle?: number;
            mechanic?: number;
            /** Format: date */
            maintenance_date?: string;
            maintenance_type?: components["schemas"]["MaintenanceTypeEnum"];
            /** Format: double */
            cost?: number;
            notes?: string;
        };
        PatchedMechanicRequest: {
            name?: string;
            certification_number?: string;
            is_active?: boolean;
        };
        PatchedOfficeRequest: {
            name?: string;
            city?: string;
        };
        /** @description Vehicle edits. Moving to another office goes through the assign endpoint. */
        PatchedVehicleUpdateRequest: {
            vin?: string;
            license_plate?: string;
            make?: string;
            model?: string;
            /** Format: int64 */
            year?: number;
            is_active?: boolean;
        };
        /**
         * @description * `ok` - ok
         *     * `error` - error
         * @enum {string}
         */
        StatusEnum: "ok" | "error";
        TokenObtainPair: {
            readonly access: string;
            readonly refresh: string;
        };
        TokenObtainPairRequest: {
            username: string;
            password: string;
        };
        TokenRefresh: {
            readonly access: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        Vehicle: {
            readonly id: number;
            vin: string;
            license_plate: string;
            make: string;
            model: string;
            /** Format: int64 */
            year: number;
            office: number;
            readonly office_name: string;
            is_active?: boolean;
        };
        VehicleDetail: {
            readonly id: number;
            vin: string;
            license_plate: string;
            make: string;
            model: string;
            /** Format: int64 */
            year: number;
            is_active?: boolean;
            readonly office: components["schemas"]["Office"];
            readonly maintenance_records: components["schemas"]["VehicleMaintenanceRecord"][];
        };
        /** @description A maintenance record shown in the context of its vehicle, with the mechanic expanded. */
        VehicleMaintenanceRecord: {
            readonly id: number;
            /** Format: date */
            maintenance_date: string;
            maintenance_type: components["schemas"]["MaintenanceTypeEnum"];
            /** Format: double */
            cost: number;
            notes?: string;
            readonly mechanic: components["schemas"]["Mechanic"];
        };
        VehicleNeedingMaintenance: {
            readonly id: number;
            vin: string;
            license_plate: string;
            make: string;
            model: string;
            /** Format: int64 */
            year: number;
            office: number;
            readonly office_name: string;
            is_active?: boolean;
            /** Format: date */
            readonly last_maintenance_date: string | null;
        };
        VehicleOfficeAssignmentRequest: {
            office: number;
        };
        VehicleRequest: {
            vin: string;
            license_plate: string;
            make: string;
            model: string;
            /** Format: int64 */
            year: number;
            office: number;
            is_active?: boolean;
        };
        /** @description Vehicle edits. Moving to another office goes through the assign endpoint. */
        VehicleUpdate: {
            readonly id: number;
            vin: string;
            license_plate: string;
            make: string;
            model: string;
            /** Format: int64 */
            year: number;
            readonly office: number;
            readonly office_name: string;
            is_active?: boolean;
        };
        /** @description Vehicle edits. Moving to another office goes through the assign endpoint. */
        VehicleUpdateRequest: {
            vin: string;
            license_plate: string;
            make: string;
            model: string;
            /** Format: int64 */
            year: number;
            is_active?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["TokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthCheck"];
                };
            };
        };
    };
    maintenance_records_list: {
        parameters: {
            query?: {
                /**
                 * @description * `oil_change` - Oil change
                 *     * `tire_rotation` - Tire rotation
                 *     * `brake_service` - Brake service
                 *     * `inspection` - Inspection
                 *     * `engine_repair` - Engine repair
                 *     * `transmission_service` - Transmission service
                 *     * `battery` - Battery
                 *     * `other` - Other
                 */
                maintenance_type?: "battery" | "brake_service" | "engine_repair" | "inspection" | "oil_change" | "other" | "tire_rotation" | "transmission_service";
                mechanic?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                vehicle?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMaintenanceRecordList"];
                };
            };
        };
    };
    maintenance_records_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceRecordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MaintenanceRecordRequest"];
                "multipart/form-data": components["schemas"]["MaintenanceRecordRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceRecord"];
                };
            };
        };
    };
    maintenance_records_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this maintenance record. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceRecord"];
                };
            };
        };
    };
    maintenance_records_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this maintenance record. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceRecordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MaintenanceRecordRequest"];
                "multipart/form-data": components["schemas"]["MaintenanceRecordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceRecord"];
                };
            };
        };
    };
    maintenance_records_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this maintenance record. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    maintenance_records_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this maintenance record. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMaintenanceRecordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMaintenanceRecordRequest"];
                "multipart/form-data": components["schemas"]["PatchedMaintenanceRecordRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceRecord"];
                };
            };
        };
    };
    mechanics_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMechanicList"];
                };
            };
        };
    };
    mechanics_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MechanicRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MechanicRequest"];
                "multipart/form-data": components["schemas"]["MechanicRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mechanic"];
                };
            };
        };
    };
    mechanics_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this mechanic. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mechanic"];
                };
            };
        };
    };
    mechanics_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this mechanic. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MechanicRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MechanicRequest"];
                "multipart/form-data": components["schemas"]["MechanicRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mechanic"];
                };
            };
        };
    };
    mechanics_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this mechanic. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The mechanic has maintenance records. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    mechanics_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this mechanic. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMechanicRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMechanicRequest"];
                "multipart/form-data": components["schemas"]["PatchedMechanicRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mechanic"];
                };
            };
        };
    };
    mechanics_workload_list: {
        parameters: {
            query?: {
                /** @description Calendar year to report on. Defaults to the current year. */
                year?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MechanicWorkload"][];
                };
            };
        };
    };
    offices_list: {
        parameters: {
            query?: {
                city?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedOfficeList"];
                };
            };
        };
    };
    offices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OfficeRequest"];
                "multipart/form-data": components["schemas"]["OfficeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Office"];
                };
            };
        };
    };
    offices_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this office. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Office"];
                };
            };
        };
    };
    offices_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this office. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OfficeRequest"];
                "multipart/form-data": components["schemas"]["OfficeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Office"];
                };
            };
        };
    };
    offices_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this office. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The office still has vehicles assigned to it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorDetail"];
                };
            };
        };
    };
    offices_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this office. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOfficeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOfficeRequest"];
                "multipart/form-data": components["schemas"]["PatchedOfficeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Office"];
                };
            };
        };
    };
    offices_summary_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficeSummary"][];
                };
            };
        };
    };
    vehicles_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Has maintenance on or after this date (YYYY-MM-DD). */
                maintenance_date_from?: string;
                /** @description Has maintenance on or before this date (YYYY-MM-DD). */
                maintenance_date_to?: string;
                make?: string;
                /** @description Has maintenance performed by the mechanic with this certification number. */
                mechanic_certification?: string;
                model?: string;
                office?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVehicleList"];
                };
            };
        };
    };
    vehicles_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VehicleRequest"];
                "multipart/form-data": components["schemas"]["VehicleRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    vehicles_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this vehicle. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleDetail"];
                };
            };
        };
    };
    vehicles_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this vehicle. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VehicleUpdateRequest"];
                "multipart/form-data": components["schemas"]["VehicleUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleUpdate"];
                };
            };
        };
    };
    vehicles_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this vehicle. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    vehicles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this vehicle. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedVehicleUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedVehicleUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedVehicleUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleUpdate"];
                };
            };
        };
    };
    vehicles_assign_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this vehicle. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VehicleOfficeAssignmentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VehicleOfficeAssignmentRequest"];
                "multipart/form-data": components["schemas"]["VehicleOfficeAssignmentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    vehicles_maintenance_history_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this vehicle. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVehicleMaintenanceRecordList"];
                };
            };
        };
    };
    vehicles_duplicate_check_retrieve: {
        parameters: {
            query?: {
                /** @description Vehicle being edited, so it is not reported as conflicting with itself. */
                exclude_id?: number;
                license_plate?: string;
                vin?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCheck"];
                };
            };
        };
    };
    vehicles_needing_maintenance_list: {
        parameters: {
            query?: {
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedVehicleNeedingMaintenanceList"];
                };
            };
        };
    };
}
